# Site settings
title: RE:code
#email: your-email@example.com
description: >-
  Welcome to a stunningly boring and unoriginal personal blog
  primarily about reverse code engineering and binary exploitation.
baseurl: ""
url: ""
#twitter_username: jekyllrb
github_username:  theofilospechlivanis

# Build settings
markdown: CommonMarkGhPages
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
