baseURL: "https://theopechli.github.io/"
languageCode: "en-us"
title: "theopechli"
theme: "PaperMod"

pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  keywords: [Blog]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true
    disableFingerprinting: true

  homeInfoParams:
    Title: "Contact Info"

  socialIcons:
    - name: github
      url: "https://github.com/theopechli"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

menu:
  main:
    - name: "Archive"
      url: "/archives/"
      weight: 5
    - name: "Categories"
      url: "/categories/"
      weight: 10
    - name: "Tags"
      url: "/tags/"
      weight: 10

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: monokai
